server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ecommerce.model
jwt:
  secret: ${JWT_SECRET}
  master-key: ${MASTER_KEY:}
  access-exp-ms: ${ACCESS_TOKEN_EXP_MS:900000}
  refresh-exp-ms: ${REFRESH_TOKEN_EXP_MS:604800000}
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

